version: '3'

volumes: 
  mongodb_volume:

services:
  server:
    container_name: node-twitter-server
    restart: always
    build: .
    ports:
      - '5000:5000'
    links: 
      - mongo
    environment: 
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/
      - TWITTER_API_KEY=
      - TWITTER_API_SECRET_KEY=
      - TWITTER_TOKEN=
      - TWITTER_TOKEN_SECRET=

  mongo:
    container_name: node-twitter-mongo
    hostname: mongo
    image: mongo
    volumes:
    - mongodb_volume:/data/db
    restart: always
    ports:
      - "27017:27017"
